# Sample Queries for Testing Patent Search Models

queries = [
    "smartphone screen technology",
    "renewable energy storage systems",
    "water purification methods",
    "virtual reality gaming devices",
    "autonomous vehicle navigation systems",
    "biodegradable packaging materials",
    "robotic surgery equipment",
    "wireless charging techniques",
    "AI algorithms for data analysis",
    "blockchain technology in banking",
    "wearable fitness trackers",
    "3D printing in construction",
    "gene editing tools",
    "quantum computing processors",
    "augmented reality in education",
    "voice recognition software",
    "solar panel innovations",
    "smart home automation systems",
    "drone delivery services",
    "machine learning in healthcare diagnostics",
    "cybersecurity for IoT devices",
    "non-invasive glucose monitoring",
    "virtual meeting technology",
    "battery life extension methods",
    "recycling techniques for plastics",
    "earthquake resistant building structures",
    "self-healing materials",
    "underwater exploration drones",
    "adaptive traffic control systems",
    "wearable technology for health monitoring",
    "predictive analytics in finance",
    "electric aircraft propulsion",
    "agricultural robots and automation",
    "mRNA vaccine development",
    "nanotechnology in medicine",
    "artificial photosynthesis",
    "next-generation wireless networks",
    "autonomous underwater vehicles",
    "personalized learning algorithms",
    "carbon capture and storage",
    "smart contact lenses",
    "language translation software",
    "high-speed rail systems",
    "sustainable urban planning",
    "smart fabrics and textiles",
    "precision agriculture technologies",
    "space tourism vehicles",
    "implantable medical devices",
    "geothermal energy extraction",
    "virtual reality in therapy",
    "augmented reality shopping experiences",
    "cloud computing security",
    "deep sea mining technology",
    "emotional recognition AI",
    "advanced prosthetics",
    "contactless payment systems",
    "microbial fuel cells",
    "smart road technologies",
    "autonomous industrial robots",
    "digital twin technology",
    "3D bioprinting organs",
    "fusion energy research",
    "hypersonic travel technology",
    "AI in predictive maintenance",
    "virtual assistants in healthcare",
    "internet of things in agriculture",
    "wearable air purifiers",
    "adaptive learning technology",
    "non-lethal crowd control devices",
    "facial recognition systems",
    "offshore wind energy",
    "magnetic levitation transportation",
    "quantum encryption methods",
    "virtual reality in architecture",
    "nanobots in cancer treatment",
    "esports technology advancements",
    "bionic eye implants",
    "wireless mesh networks",
    "smart pill technology",
    "autonomous farming equipment",
    "sustainable fishing technologies",
    "augmented reality in retail",
    "low-latency satellite internet",
    "AI-driven content creation",
    "digital health passports",
    "eco-friendly road materials",
    "robotic exoskeletons for rehabilitation",
    "portable water desalination devices",
    "AI for environmental monitoring",
    "urban air mobility solutions",
    "brain-computer interfaces",
    "zero-emission transportation",
    "personalized nutrition algorithms",
    "smart dust technology",
    "virtual reality in real estate",
    "wearable technology for pets",
    "AI in logistics and supply chain",
    "energy-efficient building designs",
    "non-invasive brain therapy",
    "quantum computing in cryptography",
    "biofuel production techniques",
    "3D printing in aerospace",
    "smart agriculture sensors",
    "autonomous cargo ships",
    "reusable rocket technology"
]

# Exporting to a file
with open('patent_queries.txt', 'w') as file:
    for query in queries:
        file.write(f"{query}\n")

print("100 patent-related queries have been saved to 'patent_queries.txt'")
